### ISSUE TITLE
Feature request: make keyboard shortcuts which allow to jump from one stage to another

### ISSUE THREAD

**Issue by ashipunov** [trufanov-nok/scantailor#12]
It is needed frequently, but the only way is a mouse. This is sometimes problematic, for example, because size of the top left panel changes and you frequently click on the wrong stage.
Suggestion: make keyboard shortcuts, saying, Ctrl+1, Ctrl+2 etc. to move between processing stages. That will speed up the work significantly.

**Comment by trufanov-nok** [comment]
It seems ST U have inherited such hotkeys from ST Enhanced. They are: O,E,N,V,K,P. I'll change them to Ctrl+1,...Ctrl+6 as required.

**Comment by ashipunov** [comment]
That would be nice! And much more intuitive, too. Thanks.

2017-09-25 17:06 GMT-05:00 Alexander Trufanov <notifications@github.com>:
