### ISSUE TITLE
Bug: "Order by mode" does not allow to keep focus

### ISSUE THREAD

**Issue by ashipunov** [trufanov-nok/scantailor#15]
When you order by mode, it is somehow almost impossible to select pages by clicking on them, they always go out of the focus. Probably this is because ST constantly (and wrongly) outputs selected pages and therefore sorting mechanism for some reason moves them to other mode group.
It is related with another issues which I will report immediately.

**Comment by trufanov-nok** [comment]
But I think this is a default behavior for all STs including original one.
App need to know value (width/height or mode) of page to sort it. But it doesn't know till it process the page. So if you apply page order to incompletely processed project only pages that are processed (have valid thumbnails) are actually sorted. All pages that unprocessed yet (with question marks on thumbnails) are moved to the tail. One you select previously unprocessed page - it got processed and ST sticks it into the right position. Thus it jumps.

You can workaround this if you batch process all pages beforehand so they get valid values and won't jump. Then apply ordering.
And my point is: original ST behaves the same way.

**Comment by ashipunov** [comment]
I understand (the only note is that original ST does not behave the same way because there is no sorting by mode, this is invention of STU). However, this makes the ordering by mode virtually useless since ST will always develop selected pages and therefore jumps.
My suggestion is to remove ordering by mode, this will clear interface and will not distract new users.
Another solution is to allow user to stop developing selected pages -- see https://github.com/trufanov-nok/scantailor/issues/16 . If that will be implemented, then this issue will be solved automatically.

**Comment by trufanov-nok** [comment]
Should be fixed with https://github.com/trufanov-nok/scantailor/commit/2977db9f10a9f408b1a251c1538429e0beaccc83

**Comment by ashipunov** [comment]
Thank you, I will try to check soon.

AS

2017-10-08 9:34 GMT-05:00 Alexander Trufanov <notifications@github.com>:

**Comment by ashipunov** [comment]
OK, now I see no jumps. Thank you!

AS

2017-10-08 22:25 GMT-05:00 Alexey Shipunov <dactylorhiza@gmail.com>:
