### ISSUE TITLE
Feature request: keep page selection between stages

### ISSUE THREAD

**Issue by ashipunov** [trufanov-nok/scantailor#18]
When you change from stage to stage, the page selection disappears. As far as I remember, that was not an original behavior of ST.

Suggestion: from "Deskew" stage, it is useful to keep page selection. This will improve the quality and speed of book processing.

**Comment by trufanov-nok** [comment]
Could you test
https://github.com/trufanov-nok/scantailor/commit/81c21b2b57a42113fe246d29f1ae2388dddc24ec
Should work but there is one known issue described [here](http://publ.lib.ru/cgi/forum/YaBB.pl?num=1505152856/233#233)

**Comment by ashipunov** [comment]
Thank you, I will try to check soon.

AS

2017-10-08 9:28 GMT-05:00 Alexander Trufanov <notifications@github.com>:

**Comment by ashipunov** [comment]
Wonderful! That works well! I agree with the logic implemented.

AS


2017-10-08 22:26 GMT-05:00 Alexey Shipunov <dactylorhiza@gmail.com>:
