### ISSUE TITLE
Problem: red asterisk on some thumbnails.

### ISSUE THREAD

**Issue by ashipunov** [trufanov-nok/scantailor#2]
This is likely the sign of "something wrong". However, the logic is not clear and what is worse, not every "wrong" page is labeled with red asterisk.
Suggestion: disable or make optional.

**Comment by trufanov-nok** [comment]
> the logic is not clear and what is worse, not every "wrong" page is labeled with red asterisk.

Have posted (in russian) the algorithm details (as I understand them) [here](http://publ.lib.ru/cgi/forum/YaBB.pl?num=1505152856/151#151).

**Comment by ashipunov** [comment]
OK, thank you! Looks like this (1) should be explained somewhere within a
program and (2) there should be a way (likely in settings) to tune these
parameters / formulas.

AS

2017-09-25 20:05 GMT-05:00 Alexander Trufanov <notifications@github.com>:

**Comment by ashipunov** [comment]
(3) + of course, way to switch this off.

AS

2017-09-25 20:20 GMT-05:00 Alexey Shipunov <dactylorhiza@gmail.com>:

**Comment by trufanov-nok** [comment]
Could be disabled in settings. Disabled by default
https://github.com/trufanov-nok/scantailor/commit/1d918e383a375ddd705fbddba29131d99c0ac3e1
