### ISSUE TITLE
Feature request: allow to enlarge thumbnails

### ISSUE THREAD

**Issue by ashipunov** [trufanov-nok/scantailor#20]
This is especially important when you check how mixed zones were set. The ability to increase the size of thumbnails will significantly improve both speed of work and quality of result.

**Comment by trufanov-nok** [comment]
Thumbnail view items alignment have been reworked. Settings to fine tune it has been added. Also Alt+Mouse wheel could be used to zoom thumbnails at runtime. Note the cached image quality setting in settings window and its description if you are looking for small details in thumbnails.
