### ISSUE TITLE
Bug: text does not copy from "About/About" window, plus small issues

### ISSUE THREAD

**Issue by ashipunov** [trufanov-nok/scantailor#29]
Cursor is in this window is for some reason cross-shaped, text does not copy. I know that copying is possible because I use Qt programs like TeXWorks where it does work.

Also, instead of date it would be better to mention some number which refers to the exact version

Also, there is likely a misprint and not a correct phrase: "build fromSep 15 2017" is better to replace with "build on Sep 15, 2017" (but version number is even better).

**Comment by trufanov-nok** [comment]
I've fixed About dialog, will change versioning later

**Comment by ashipunov** [comment]
Thank you!

**Comment by ashipunov** [comment]
The newly built Scan Tailor 'Universal" 0.0.1 does not allow to copy its name from "About" window. Therefore, it adds a difficulty when one needs to report an issue.

**Comment by trufanov-nok** [comment]
Should be fixed now in current master

**Comment by ashipunov** [comment]
Works now, thanks! However, version numbering does not reflect your
changes. Example: you just corrected this copying problem, but version
number is still 0.0.1. How to refer to the changed version? This is unclear.

AS

2017-09-26 2:23 GMT-05:00 Alexander Trufanov <notifications@github.com>:
