### ISSUE TITLE
Problem: "Batch Process" dialog is not placed well

### ISSUE THREAD

**Issue by ashipunov** [trufanov-nok/scantailor#3]
Now, there is "Remember my choice" button. However, what to do if one decided first on one choice, and then changed the mind? Start the project from scratch?
Suggestion: please move choice into settings, and remove this dialog completely by default. The defauld behavior should be "Start from selected" like in earlier versions.

**Comment by trufanov-nok** [comment]
Moved to settings. Defaults are set.
https://github.com/trufanov-nok/scantailor/commit/5bc7c64f528128b3af102b75ba8e8767b3cd6405
