### ISSUE TITLE
Bug: the sorting order changes when I select pages on "Margin" stage

### ISSUE THREAD

**Issue by ashipunov** [trufanov-nok/scantailor#37]
I frequently select shorter pages with big images ("tables", common, for example in palaeontological literature) and then center them vertically, they look much better after centering. Today I tried to do this in Scan Tailor "Universal" (compiled from master 20 minutes ago) but when I select the thumbnail, it randomly jumps to some new position. Sometimes, it does not jump. Sometimes, other pages jump. This reminds me of earlier problem (https://github.com/trufanov-nok/scantailor/issues/15). It also makes STU _less_ usable then previous versions.

**Comment by trufanov-nok** [comment]
#15 is closed and this should be fixed too
