### ISSUE TITLE
Feature request: Please separate binarization treshold from "Mode"

### ISSUE THREAD

**Issue by ashipunov** [trufanov-nok/scantailor#38]
On the "Output" stage, binarization threshold relates with two modes: Black and White and Mixed. Therefore, it is much more logical to make this choice separate from mode choice. Then you might, for example, apply same binarizarion threshold to selected mixed and bw pages without tiresome work of changing mode back again.

**Comment by trufanov-nok** [comment]
As a part of this change I've suggested a new UI for left panel on a last step. Could you pls check it in dev branch and post your opinion in [this](http://publ.lib.ru/cgi/forum/YaBB.pl?num=1505152856/189#189) thread.

**Comment by ashipunov** [comment]
Thank you. I will look on it when I have a time.

2017-09-29 6:15 GMT-05:00 Alexander Trufanov <notifications@github.com>:

**Comment by ashipunov** [comment]
Done.

Actually, I would prefer to use Github if possible. This forum is buggy and
not available to everybody because it is in Russian. Also, recently there
were problems when significant portion of messages were lost. Github is
younger but looks a bit more sustainable.

But the way, do I need to open bug issue about "Apply to"?

AS

2017-09-29 20:56 GMT-05:00 Alexey Shipunov <dactylorhiza@gmail.com>:
