### ISSUE TITLE
Bug: "Beep when finished" does not work

### ISSUE THREAD

**Issue by ashipunov** [trufanov-nok/scantailor#5]
On my computer, whet "Select Content" runs, check box is on, sound is on but no beep produced.

This is not specific to STU, the same problem I saw on earlier versions of Scan Tailor.

**Comment by trufanov-nok** [comment]
Confirmed. Looks like `QApplication:beep()` doesn't work with some Linux sound system configurations. That's a Qt framework problem. And as we're sticked to old Qt4 libraries, It seems that reliable fix is to use QMediaPlayer and add required Qt4Multimedia.dll to distributive. 

Or we can rely on some system tool and execute something external without GUI, like "play /usr/share/sounds/freedesktop/stereo/bell.oga". And store actual command in settings.ini. I think this is a most feasible and flexible solution.

**Comment by ashipunov** [comment]
OK, thanks. Second way, I think, is preferable. Also, it should be nice to place in settings.

**Comment by ashipunov** [comment]
Wonderful, many thanks!

**Comment by ashipunov** [comment]
Sorry, but beep is not working again with Scan Tailor "Universal" 0.0.1

**Comment by trufanov-nok** [comment]
Yep. It got broken when I've switched to qt5. Now it should work fine.

**Comment by ashipunov** [comment]
Now works, thanks!!

AS

2017-09-26 2:38 GMT-05:00 Alexander Trufanov <notifications@github.com>:

**Comment by ashipunov** [comment]
Sorry, does not work again... (Executable compiled 5 minutes ago).

AS

2017-09-26 22:03 GMT-05:00 Alexey Shipunov <dactylorhiza@gmail.com>:

**Comment by ashipunov** [comment]
1. No
2. Works
3."This program uses Qt version 5.5.1."

2017-09-27 9:27 GMT-05:00 Alexander Trufanov <notifications@github.com>:

**Comment by trufanov-nok** [comment]
Can't reproduce yet...

**Comment by trufanov-nok** [comment]
Is there any output to console if you launch ST from terminal and play this alarm sound?

**Comment by ashipunov** [comment]
It actually plays sound! But NOT on my laptop which is almost exact
copy of my desktop which I used for testing.

However, on my laptop this morning, to answer "2. Works", instead of
"play /usr/share/sounds/freedesktop/stereo/bell.oga" I run "mpv
/usr/share/sounds/freedesktop/stereo/bell.oga" because "play" is not
installed there:

===
$ play
The program 'play' is currently not installed. You can install it by typing:
sudo apt install sox
===

Is this why there is no beep? Is the only way to get a beep to install
"play"? Please note that "play" is not installed by default on Ubuntu
16.04, even with all Qt5 dev libraries which are using to compile Scan
Tailor Universal.

(Sorry, in the morning I had no time to write all details and now, I
am away from laptop).

AS

2017-09-27 10:51 GMT-05:00 Alexander Trufanov <notifications@github.com>:

**Comment by trufanov-nok** [comment]
Currently you can edit `~/.config/Scan\ Tailor\ Universal/Scan\ Tailor\ Universal.ini` file
and add `external_alarm_cmd=mpv /usr/share/sounds/freedesktop/stereo/bell.oga` line in `[main_window]` section to overwrite default command.

It seems most default thing that allows user to play a sound from command line is a `/usr/local/bin/aplay` which is part of `alsa-utils`. It could be tested with `aplay /usr/share/sounds/alsa/Noise.wav`
Unfortunately it can't play .oga or .ogg files. And there is nothing better then Noise.wav by default in supported formats.

So, you can edit default command in ini (probably, try `paplay` instead of `mpv`).
But I'll need to think out more portable way in feature. Probably link to Qt5Multimedia or place suitable wav in application distributive.

**Comment by ashipunov** [comment]
Thanks for the detailed explanation. I only can add here that the best
location of this setting would be not just ini but "Settings..." window --
because ST shows this "play sound" explicitly, on all batch screens.

AS

2017-09-27 20:26 GMT-05:00 Alexander Trufanov <notifications@github.com>:
