### ISSUE TITLE
Cooperation with 4lex4

### ISSUE THREAD

**Issue by hason** [trufanov-nok/scantailor#58]
Hi, I found a promising https://github.com/4lex4/scantailor-advanced fork and it would be great to combine the effort.

**Comment by trufanov-nok** [comment]
Hi, I'm aware of it. We got in touch few months ago. As I'm listed in STA's About dialog I guess some STF features were used there. After my last look into STA's codebase I found some features that I might want to adapt for STF in a coming months.
But I think I might have different approach for GUI and user experience. And thus projects might target different user groups. And influenced by different discussion boards. Thus I expect projects become more different in UI and UX in feature.
So, we already have some level of collaboration and I think it's a best option.

**Comment by daa2018** [comment]
The discussion board mentioned here is 

http://publ.lib.ru/cgi/forum/YaBB.pl?num=1505152856/375#375
