### ISSUE TITLE
I am getting Unknown Cmake command

### ISSUE THREAD

**Issue by Dellu** [trufanov-nok/scantailor#60]
```
CMake Error at dewarping/CMakeLists.txt:20 (QT5_USE_MODULES):
  Unknown CMake command "QT5_USE_MODULES".
```

Mac OS 10.13.4

**Comment by trufanov-nok** [comment]
You need to install following modules via brew: `cmake qt boost jpeg libtiff libpng`

**Comment by trufanov-nok** [comment]
Well, seems you need to specify some paths for cmake during compilation. I would recommend one of these options:
1. Use prebuild distribution in dmg image [here](https://github.com/trufanov-nok/scantailor/releases)
2. Try 
```
brew tap trufanov-nok/scantailor-universal
brew install scantailor-universal
```
I'm not promoting this a lot coz I'm having a crash report on ST close if it's build this way. Mac isn't a primary platform for me (Linux is) so I'm testing on old Mac virual machine - this may be the reason.
And STU version in my local homebrew is outdated a bit. Let me know if this way works and I update it.

3. Wait some time while I find the right cmake params and post them here.

**Comment by Dellu** [comment]
I didn't know that you have already built it to DMG file. 

Well, what can I ask better than this?

Thank you very much!!
