### ISSUE TITLE
Problem: Build failed on Gentoo Linux x32

### ISSUE THREAD

**Issue by eugeny54** [trufanov-nok/scantailor#62]
0. Check prerequisites:
=sys-devel/gcc-4.9.4
=dev-util/cmake-3.6.3
=media-libs/libjpeg-turbo-1.5.0
=sys-libs/zlib-1.2.8-r1
=media-libs/libpng-1.6.27
=media-libs/tiff-4.0.7
=dev-libs/boost-1.56.0-r1
1. Download scantailor-0.2.7.tgz from Releases and unpacked it to /home/eugeny54/tmpfs/
3. Change dir to /home/eugeny54/tmpfs/scantailor-0.2.7/ and 'mkdir build'
4. Change dir to /home/eugeny54/tmpfs/scantailor-0.2.7/build/ and runs 'cmake ..'
5. Run 'make'
....
[ 88%] Building CXX object CMakeFiles/scantailor.dir/MainWindow.cpp.o
/home/eugeny54/tmpfs/scantailor-0.2.7/MainWindow.cpp: In member function 'virtual bool MainWindow::eventFilter(QObject*, QEvent*)':
/home/eugeny54/tmpfs/scantailor-0.2.7/MainWindow.cpp:690:49: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 if (filter->selectedPageOrder() >= filter->pageOrderOptions().size()-2) {
                                                 ^
/home/eugeny54/tmpfs/scantailor-0.2.7/MainWindow.cpp:695:49: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 if (filter->selectedPageOrder() == filter->pageOrderOptions().size()-1) {
                                                 ^
/home/eugeny54/tmpfs/scantailor-0.2.7/MainWindow.cpp: In member function 'void MainWindow::exportDialogClosed(QObject*)':
/home/eugeny54/tmpfs/scantailor-0.2.7/MainWindow.cpp:2019:39: error: 'ExportDialog::PageGenTweaks' has no member named 'setFlag'
     m_export_settings.page_gen_tweaks.setFlag(ExportDialog::PageGenTweak::KeepOriginalColorIllumForeSubscans, false);
                                       ^
/home/eugeny54/tmpfs/scantailor-0.2.7/MainWindow.cpp:2020:39: error: 'ExportDialog::PageGenTweaks' has no member named 'setFlag'
     m_export_settings.page_gen_tweaks.setFlag(ExportDialog::PageGenTweak::IgnoreOutputProcessingStage, false);
                                       ^
/home/eugeny54/tmpfs/scantailor-0.2.7/MainWindow.cpp: In member function 'void MainWindow::filterResult(const BackgroundTaskPtr&, const FilterResultPtr&)':
/home/eugeny54/tmpfs/scantailor-0.2.7/MainWindow.cpp:1733:60: warning: ignoring return value of 'int system(const char*)', declared with attribute warn_unused_result [-Wunused-result]
                      std::system(cmd.toStdString().c_str());
                                                            ^
CMakeFiles/scantailor.dir/build.make:570: recipe for target 'CMakeFiles/scantailor.dir/MainWindow.cpp.o' failed
make[2]: *** [CMakeFiles/scantailor.dir/MainWindow.cpp.o] Error 1
CMakeFiles/Makefile2:118: recipe for target 'CMakeFiles/scantailor.dir/all' failed
make[1]: *** [CMakeFiles/scantailor.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by trufanov-nok** [comment]
You need Qt version 5.7 or newer to build it with this function
https://doc.qt.io/QT-5/qflags.html#setFlag
