### ISSUE TITLE
Scantailor-cli: "terminate called after throwing an instance of 'char const*'"

### ISSUE THREAD

**Issue by GipHub123** [trufanov-nok/scantailor#70]
Hi,

I'm not sure if this is a bug or just my own inability to compile the code / libraries.
I've been trying to run scantailor-cli on amazonlinux (AWS lambda). Scantailor version is 0.2.7. 

Compilation succeeds but with some warnings and I'm not sure which are relevant. 
After the compilation command "scantailor-cli" prints out the help related text as it should. 
But when I try "scantailor-cli <folder> <folder>" with any kind of images, I got an error message: 
terminate called after throwing an instance of 'char const*'

I've also tried to compile all libraries from the source codes but the result seems always to be the same. I ran test cases and one seemed to failed. 

I attached docker file / docker related files so it should be quite easy to reproduce the error. 

Regards,
-V-

[Dockerfile.zip](https://github.com/trufanov-nok/scantailor/files/3995047/Dockerfile.zip)
[docker_log.txt](https://github.com/trufanov-nok/scantailor/files/3995048/docker_log.txt)

**Comment by trufanov-nok** [comment]
That's bcs https://github.com/trufanov-nok/scantailor/archive/0.2.7.tar.gz is missing some source files. At least this subfolder is missing:
https://github.com/trufanov-nok/scantailor/tree/master/filters/output/resources

As the files are listed on github.com they are commited. Both tar.gz and zip files with code were created automatically via GitHubs web interface by pressing Release button - I don't know how this could be possible. I'll ask github's tech support to clarify this.

**Comment by trufanov-nok** [comment]
Looks like I just forgot that I'd already fixed this problem. It was reported here: https://github.com/trufanov-nok/scantailor/issues/61
And the code in 0.2.7 release is more outdated than I expected.

**Comment by trufanov-nok** [comment]
Try newly added 0.2.8: https://github.com/trufanov-nok/scantailor/archive/0.2.8.tar.gz
